[package]
name = "empire-desktop"
version = "0.1.54"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
empire-daemon = { path = "../../crates/empire-daemon" }
tauri = { version = "2", features = [] }

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
