#!/usr/bin/env python3
"""Generate Rust game-data tables for ``crates/empire-game``.

The Python bot keeps its troop/tool/kingdom tables as ``Enum`` members whose
``.data`` property builds a literal dict. Those tables are the single source of
truth, so this script loads them *without importing the ``bot`` package* (which
would drag in numpy and psycopg) and emits plain Rust statics.

Run from the repository root or from ``rust_distributable``::

    python3 rust_distributable/scripts/gen_game_data.py

Outputs (all overwritten):

    crates/empire-game/src/generated/troops.rs
    crates/empire-game/src/generated/tools.rs
    crates/empire-game/src/generated/kingdoms.rs
    crates/empire-game/tests/fixtures/sands_attacks.json

The fixture holds ``Attack.to_payload()`` for every Burning Sands attack,
computed by the real Python serialiser, so the Rust port can be asserted against
it rather than against a hand-copied expectation.
"""

from __future__ import annotations

import ast
import importlib.util
import json
import sys
import types
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT = Path(__file__).resolve()
RUST_DIR = SCRIPT.parents[1]  # rust_distributable/
REPO_ROOT = RUST_DIR.parent  # empire_network_bot/
GAME_DATA = REPO_ROOT / "bot" / "game_data"
OUT_DIR = RUST_DIR / "crates" / "empire-game"

if not GAME_DATA.is_dir():
    sys.exit(f"cannot find bot/game_data at {GAME_DATA}")

# ---------------------------------------------------------------------------
# Standalone module loader
# ---------------------------------------------------------------------------
#
# attack.py does ``from .troops import Troop`` because it expects to live in a
# package. Registering a synthetic package lets every file load on its own terms
# while keeping bot/__init__.py and bot/game_data/__init__.py out of the way.

_PACKAGE = "_openauto_gamedata"
_pkg = types.ModuleType(_PACKAGE)
_pkg.__path__ = [str(GAME_DATA)]
sys.modules[_PACKAGE] = _pkg


def _load(module_name: str):
    full_name = f"{_PACKAGE}.{module_name}"
    spec = importlib.util.spec_from_file_location(full_name, GAME_DATA / f"{module_name}.py")
    if spec is None or spec.loader is None:
        sys.exit(f"cannot load {module_name}.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[full_name] = module
    spec.loader.exec_module(module)
    return module


troops_mod = _load("troops")
tools_mod = _load("tools")
kingdom_mod = _load("kingdom")
attack_mod = _load("attack")

Troop = troops_mod.Troop
Tool = tools_mod.Tool
Kingdom = kingdom_mod.Kingdom
Attack = attack_mod.Attack
side = attack_mod.side
wave = attack_mod.wave

# ---------------------------------------------------------------------------
# Rust emission helpers
# ---------------------------------------------------------------------------


def rust_str(value: str) -> str:
    """A Rust string literal. json.dumps is a valid subset for our ASCII names."""

    return json.dumps(value)


def rust_option(value) -> str:
    return "None" if value is None else f"Some({int(value)})"


def write(path: Path, text: str, header: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    banner = (
        f"// @generated by scripts/gen_game_data.py -- do not edit by hand.\n"
        f"// Source: bot/game_data/{header}\n"
        f"// Re-run: python3 rust_distributable/scripts/gen_game_data.py\n\n"
    )
    path.write_text(banner + text, encoding="utf-8")
    print(f"wrote {path.relative_to(RUST_DIR)} ({text.count(chr(10)) + 1} lines)")


TROOP_FIELDS = (
    "id",
    "name",
    "attack_power",
    "melee_defence",
    "ranged_defence",
    "loot_capacity",
    "travel_speed",
)

# ---------------------------------------------------------------------------
# Troops
# ---------------------------------------------------------------------------


def generate_troops() -> int:
    rows = []
    for member in Troop:
        data = member.data
        missing = [field for field in TROOP_FIELDS if field not in data]
        if missing:
            sys.exit(f"troop {member.name} is missing {missing}")
        if data["name"] != member.value:
            sys.exit(f"troop {member.name}: name {data['name']!r} != {member.value!r}")
        rows.append(
            (
                member.value,
                data,
            )
        )

    ids = [data["id"] for _, data in rows]
    if len(set(ids)) != len(ids):
        sys.exit("duplicate troop ids")

    rows.sort(key=lambda row: row[0])

    entries = []
    for name, data in rows:
        entries.append(
            "    TroopStats {\n"
            f"        id: {data['id']},\n"
            f"        name: {rust_str(name)},\n"
            f"        attack_power: {data['attack_power']},\n"
            f"        melee_defence: {data['melee_defence']},\n"
            f"        ranged_defence: {data['ranged_defence']},\n"
            f"        loot_capacity: {data['loot_capacity']},\n"
            f"        travel_speed: {data['travel_speed']},\n"
            f"        food_consumption: {rust_option(data.get('food_consumption'))},\n"
            f"        mead_consumption: {rust_option(data.get('mead_consumption'))},\n"
            "    },"
        )

    body = (
        "use serde::Serialize;\n\n"
        "/// Combat stats for one trainable or event unit.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]\n"
        "pub struct TroopStats {\n"
        "    pub id: i64,\n"
        "    pub name: &'static str,\n"
        "    pub attack_power: i64,\n"
        "    pub melee_defence: i64,\n"
        "    pub ranged_defence: i64,\n"
        "    pub loot_capacity: i64,\n"
        "    pub travel_speed: i64,\n"
        "    /// Absent for units that do not eat.\n"
        "    pub food_consumption: Option<i64>,\n"
        "    /// Absent for units that do not drink mead.\n"
        "    pub mead_consumption: Option<i64>,\n"
        "}\n\n"
        f"/// Every known unit, sorted by name ({len(entries)} entries).\n"
        "pub static TROOPS: &[TroopStats] = &[\n" + "\n".join(entries) + "\n];\n\n"
        "/// Look a unit up by its snake_case name.\n"
        "pub fn troop_by_name(name: &str) -> Option<&'static TroopStats> {\n"
        "    TROOPS\n"
        "        .binary_search_by(|troop| troop.name.cmp(name))\n"
        "        .ok()\n"
        "        .map(|index| &TROOPS[index])\n"
        "}\n\n"
        "/// Look a unit up by its game id.\n"
        "pub fn troop_by_id(id: i64) -> Option<&'static TroopStats> {\n"
        "    TROOPS.iter().find(|troop| troop.id == id)\n"
        "}\n"
    )
    write(OUT_DIR / "src" / "generated" / "troops.rs", body, "troops.py")
    return len(entries)


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------


def generate_tools() -> int:
    rows = []
    for member in Tool:
        data = member.data
        if "id" not in data:
            sys.exit(f"tool {member.name} has no id")
        extras = sorted((key, value) for key, value in data.items() if key != "id")
        for key, value in extras:
            if not isinstance(value, int):
                sys.exit(f"tool {member.name}.{key} is not an int: {value!r}")
        rows.append((member.value, data["id"], extras))

    ids = [tool_id for _, tool_id, _ in rows]
    if len(set(ids)) != len(ids):
        sys.exit("duplicate tool ids")

    rows.sort(key=lambda row: row[0])

    entries = []
    for name, tool_id, extras in rows:
        attributes = ", ".join(f"({rust_str(key)}, {value})" for key, value in extras)
        if attributes:
            attributes = f"&[{attributes}]"
        else:
            attributes = "&[]"
        entries.append(
            "    ToolStats {\n"
            f"        id: {tool_id},\n"
            f"        name: {rust_str(name)},\n"
            f"        attributes: {attributes},\n"
            "    },"
        )

    body = (
        "use serde::Serialize;\n\n"
        "/// One combat tool.\n"
        "///\n"
        "/// Unlike troops, tools carry an open-ended set of bonus fields\n"
        "/// (`wall_reduction`, `glory_points`, `tool_limit_per_wave`, ...), so the\n"
        "/// extras are kept as a name/value list rather than a fixed struct.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]\n"
        "pub struct ToolStats {\n"
        "    pub id: i64,\n"
        "    pub name: &'static str,\n"
        "    pub attributes: &'static [(&'static str, i64)],\n"
        "}\n\n"
        "impl ToolStats {\n"
        "    /// Read one bonus field by name.\n"
        "    pub fn attribute(&self, key: &str) -> Option<i64> {\n"
        "        self.attributes\n"
        "            .iter()\n"
        "            .find(|(name, _)| *name == key)\n"
        "            .map(|(_, value)| *value)\n"
        "    }\n\n"
        "    /// The per-wave limit, where the game data defines one.\n"
        "    pub fn tool_limit_per_wave(&self) -> Option<i64> {\n"
        "        self.attribute(\"tool_limit_per_wave\")\n"
        "    }\n"
        "}\n\n"
        f"/// Every known tool, sorted by name ({len(entries)} entries).\n"
        "pub static TOOLS: &[ToolStats] = &[\n" + "\n".join(entries) + "\n];\n\n"
        "/// Look a tool up by its snake_case name.\n"
        "pub fn tool_by_name(name: &str) -> Option<&'static ToolStats> {\n"
        "    TOOLS\n"
        "        .binary_search_by(|tool| tool.name.cmp(name))\n"
        "        .ok()\n"
        "        .map(|index| &TOOLS[index])\n"
        "}\n\n"
        "/// Look a tool up by its game id.\n"
        "pub fn tool_by_id(id: i64) -> Option<&'static ToolStats> {\n"
        "    TOOLS.iter().find(|tool| tool.id == id)\n"
        "}\n"
    )
    write(OUT_DIR / "src" / "generated" / "tools.rs", body, "tools.py")
    return len(entries)


# ---------------------------------------------------------------------------
# Kingdoms
# ---------------------------------------------------------------------------


def generate_kingdoms() -> int:
    entries = []
    for member in Kingdom:
        data = member.data
        entries.append(
            "    Kingdom {\n"
            f"        id: {data['id']},\n"
            f"        name: {rust_str(data['name'])},\n"
            f"        constant: {rust_str(member.name)},\n"
            "    },"
        )

    body = (
        "use serde::Serialize;\n\n"
        "/// One game kingdom.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]\n"
        "pub struct Kingdom {\n"
        "    pub id: i64,\n"
        "    pub name: &'static str,\n"
        "    /// The Python enum member name, kept for traceability.\n"
        "    pub constant: &'static str,\n"
        "}\n\n"
        "/// Green, Sand, Ice, Fire, Storm and Berimond.\n"
        f"pub static KINGDOMS: &[Kingdom] = &[\n" + "\n".join(entries) + "\n];\n\n"
        "pub const GREEN_KINGDOM_ID: i64 = 0;\n"
        "pub const SAND_KINGDOM_ID: i64 = 1;\n"
        "pub const ICE_KINGDOM_ID: i64 = 2;\n"
        "pub const FIRE_KINGDOM_ID: i64 = 3;\n"
        "pub const STORM_KINGDOM_ID: i64 = 4;\n"
        "pub const BERIMOND_KINGDOM_ID: i64 = 10;\n\n"
        "/// Look a kingdom up by id.\n"
        "pub fn kingdom_by_id(id: i64) -> Option<&'static Kingdom> {\n"
        "    KINGDOMS.iter().find(|kingdom| kingdom.id == id)\n"
        "}\n"
    )
    write(OUT_DIR / "src" / "generated" / "kingdoms.rs", body, "kingdom.py")
    return len(entries)


# ---------------------------------------------------------------------------
# Attack payload fixture
# ---------------------------------------------------------------------------
#
# The attack definitions are read straight out of bot/event/sand/config.py with
# the ast module and evaluated against the real Attack/side/wave/Troop/Tool
# objects. Importing that module is not an option: it imports bot.scheduler,
# which pulls numpy in through bot.ranomizer. Extracting the AST keeps this
# script dependency-free while still using the genuine definitions and the
# genuine serialiser, so the fixture cannot drift from the bot -- which is
# exactly what happened when these were transcribed by hand.


def _slot_list(node: ast.AST, enum_type) -> list[tuple]:
    if not isinstance(node, ast.List):
        raise ValueError(
            f"expected a list of (member, amount) pairs, got {type(node).__name__}"
        )
    items = []
    for element in node.elts:
        if not isinstance(element, ast.Tuple) or len(element.elts) != 2:
            raise ValueError("slot entries must be (Troop.NAME, amount) pairs")
        member_node, amount_node = element.elts
        if not isinstance(member_node, ast.Attribute):
            raise ValueError("slot members must be written as Troop.NAME or Tool.NAME")
        if not isinstance(amount_node, ast.Constant) or not isinstance(
            amount_node.value, int
        ):
            raise ValueError("slot amounts must be integer literals")
        items.append((getattr(enum_type, member_node.attr), amount_node.value))
    return items


def _eval_side(node: ast.AST):
    if not isinstance(node, ast.Call) or getattr(node.func, "id", None) != "side":
        raise ValueError("expected a side(...) call")
    kwargs = {}
    for keyword in node.keywords:
        if keyword.arg == "units":
            kwargs["units"] = _slot_list(keyword.value, Troop)
        elif keyword.arg == "tools":
            kwargs["tools"] = _slot_list(keyword.value, Tool)
        else:
            raise ValueError(f"unexpected side keyword {keyword.arg!r}")
    return side(**kwargs)


def _eval_wave(node: ast.AST):
    if not isinstance(node, ast.Call) or getattr(node.func, "id", None) != "wave":
        raise ValueError("expected a wave(...) call")
    kwargs = {}
    for keyword in node.keywords:
        if keyword.arg not in {"left", "middle", "right"}:
            raise ValueError(f"unexpected wave keyword {keyword.arg!r}")
        kwargs[keyword.arg] = _eval_side(keyword.value)
    return wave(**kwargs)


def sand_attacks() -> dict[str, Attack]:
    """Every ``NAME = Attack(...)`` definition in bot/event/sand/config.py."""

    config_path = REPO_ROOT / "bot" / "event" / "sand" / "config.py"
    tree = ast.parse(config_path.read_text(encoding="utf-8"), filename=str(config_path))

    found: dict[str, Attack] = {}
    for statement in tree.body:
        if not isinstance(statement, ast.Assign) or len(statement.targets) != 1:
            continue
        target = statement.targets[0]
        call = statement.value
        if not isinstance(target, ast.Name):
            continue
        if not isinstance(call, ast.Call) or getattr(call.func, "id", None) != "Attack":
            continue
        kwargs = {}
        for keyword in call.keywords:
            if keyword.arg not in {"wave1", "wave2", "wave3", "wave4"}:
                raise ValueError(f"unexpected Attack keyword {keyword.arg!r}")
            kwargs[keyword.arg] = _eval_wave(keyword.value)
        found[target.id] = Attack(**kwargs)

    if not found:
        raise SystemExit(f"no Attack definitions found in {config_path}")
    return found


def generate_fixture() -> int:
    attacks = sand_attacks()
    fixture = {
        "note": (
            "Expected Attack.to_payload() output: definitions extracted from "
            "bot/event/sand/config.py, serialised by bot/game_data/attack.py."
        ),
        "attacks": {name: {"payload": attack.to_payload()} for name, attack in attacks.items()},
    }
    path = OUT_DIR / "tests" / "fixtures" / "sands_attacks.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(RUST_DIR)}")
    return len(fixture["attacks"])


def main() -> None:
    troops = generate_troops()
    tools = generate_tools()
    kingdoms = generate_kingdoms()
    attacks = generate_fixture()
    print(f"\ntroops={troops} tools={tools} kingdoms={kingdoms} attacks={attacks}")
    if (troops, tools, kingdoms) != (257, 294, 6):
        sys.exit(
            f"unexpected counts: troops={troops} (want 257), tools={tools} (want 294), "
            f"kingdoms={kingdoms} (want 6)"
        )
    if attacks != 5:
        sys.exit(f"expected 5 Sands attacks in sand/config.py, extracted {attacks}")


if __name__ == "__main__":
    main()
